# Generated by Django 3.2 on 2023-01-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_historicalarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description_en',
            field=models.TextField(max_length=255, null=True, verbose_name='Описание статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='description_ru',
            field=models.TextField(max_length=255, null=True, verbose_name='Описание статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Текст статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='Текст статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок статьи'),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок статьи'),
        ),
    ]
