# Generated by Django 4.0.5 on 2022-06-21 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_recipe_ingredients_recipe_ingredients'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes_comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipecomment',
            options={'verbose_name': 'Комментарий к рецепту', 'verbose_name_plural': 'Комментарии к рецептам'},
        ),
        migrations.RemoveField(
            model_name='recipecomment',
            name='author',
        ),
        migrations.AddField(
            model_name='recipecomment',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='recipecomment',
            name='recipe_id',
        ),
        migrations.AddField(
            model_name='recipecomment',
            name='recipe_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='ID Рецепта'),
            preserve_default=False,
        ),
    ]
