# Generated by Django 4.0.5 on 2022-06-21 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles_comments', '0002_remove_articlecomment_author_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'verbose_name': 'Комментарий к статье', 'verbose_name_plural': 'Комментарии к статьям'},
        ),
        migrations.RemoveField(
            model_name='articlecomment',
            name='article_id',
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='article_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='articles.article', verbose_name='ID Статьи'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='articlecomment',
            name='author',
        ),
        migrations.AddField(
            model_name='articlecomment',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
            preserve_default=False,
        ),
    ]
