# Generated by Django 4.0.5 on 2022-06-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foodTypes', '0001_initial'),
        ('recipeTypes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя рецепта')),
                ('description', models.TextField(verbose_name='Описание')),
                ('ingredients', models.TextField(verbose_name='Ингредиенты')),
                ('cooking', models.TextField(verbose_name='Готовка')),
                ('food_type', models.ManyToManyField(related_name='recipes', to='foodTypes.foodtype', verbose_name='Тип еды')),
                ('recipe_type', models.ManyToManyField(related_name='recipes', to='recipeTypes.recipetype', verbose_name='Тип рецепта')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
            },
        ),
    ]
