# Generated by Django 4.0.5 on 2022-07-06 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_favouriterecipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favouriterecipe',
            old_name='RECIPE',
            new_name='recipe',
        ),
    ]
