# Generated by Django 3.2 on 2023-01-19 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20230120_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description_r',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='description_u',
            new_name='description_ru',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='name_r',
            new_name='name_en',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='name_u',
            new_name='name_ru',
        ),
    ]
