# Generated by Django 3.2 on 2023-01-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20230120_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking_en',
            field=models.TextField(null=True, verbose_name='Готовка'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_ru',
            field=models.TextField(null=True, verbose_name='Готовка'),
        ),
    ]
