# Generated by Django 3.2 on 2023-01-20 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20230120_0009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalRecipe',
        ),
    ]
